const extraImage = (id) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=82`;
window.hardwareExtras = [
  {
    id: "cooling",
    number: "13",
    name: "Refrigeración",
    short: "Temperatura bajo control",
    group: "interno",
    tag: "Temperatura",
    products: [
      {
        brand: "DeepCool",
        model: "AK400 Digital",
        price: "Q 449",
        shop: "Intelaf",
        place: "Ciudad de Guatemala",
        image: extraImage("photo-1581452980906-78a2f3b8a0c8"),
        specs: [
          ["Tipo", "Aire · torre"],
          ["Compatibilidad", "AM4 · AM5 · LGA1700"],
          ["Ventilador", "120 mm"],
          ["Ruido", "Hasta 29 dB(A)"],
        ],
        score: 9.1,
        source:
          "https://www.deepcool.com/products/Cooling/cpuaircoolers/AK400-Digital-CPU-Cooler/2022/16123.shtml",
      },
      {
        brand: "Cooler Master",
        model: "MasterLiquid ML240L V2",
        price: "Q 899",
        shop: "Pacifiko",
        place: "Cobertura nacional",
        image: extraImage("photo-1591488320449-011701bb6704"),
        specs: [
          ["Tipo", "Líquida · 240 mm"],
          ["Compatibilidad", "AM4 · AM5 · LGA1700"],
          ["Ventiladores", "2 × 120 mm"],
          ["Bomba", "Gen 3"],
        ],
        score: 9.0,
        source:
          "https://www.coolermaster.com/catalog/coolers/cpu-liquid-coolers/masterliquid-ml240l-v2-rgb/",
      },
    ],
    recommend: "DeepCool AK400 Digital",
    why: "La refrigeración por aire simplifica el mantenimiento y cubre de sobra un procesador de gama media.",
    ideal: "Gaming · oficina · armados silenciosos",
  },
  {
    id: "case",
    number: "14",
    name: "Gabinetes",
    short: "El espacio del sistema",
    group: "interno",
    tag: "Diseño",
    products: [
      {
        brand: "NZXT",
        model: "H5 Flow",
        price: "Q 899",
        shop: "Pacifiko",
        place: "Cobertura nacional",
        image: extraImage("photo-1587202372583-49330a15584d"),
        specs: [
          ["Formato", "ATX · mATX · ITX"],
          ["Panel", "Vidrio templado"],
          ["Ventiladores", "2 incluidos"],
          ["Frontal", "USB-C · USB-A"],
        ],
        score: 9.2,
        source: "https://nzxt.com/product/h5-flow",
      },
      {
        brand: "Corsair",
        model: "4000D Airflow",
        price: "Q 999",
        shop: "Intelaf",
        place: "Ciudad de Guatemala",
        image: extraImage("photo-1591488320449-011701bb6704"),
        specs: [
          ["Formato", "ATX · mATX · ITX"],
          ["Panel", "Vidrio templado"],
          ["Ventiladores", "2 incluidos"],
          ["Frontal", "USB-C · USB-A"],
        ],
        score: 9.3,
        source:
          "https://www.corsair.com/us/en/p/pc-cases/cc-9011200-ww/4000d-airflow-tempered-glass-mid-tower-atx-case-black-cc-9011200-ww",
      },
    ],
    recommend: "NZXT H5 Flow",
    why: "Equilibra flujo de aire, tamaño y organización de cables para un primer armado limpio.",
    ideal: "Primer PC · gaming · upgrades",
  },
  {
    id: "fans",
    number: "15",
    name: "Ventiladores",
    short: "Flujo que no se ve",
    group: "interno",
    tag: "Silencio",
    products: [
      {
        brand: "Arctic",
        model: "P12 PWM PST 120 mm",
        price: "Q 119",
        shop: "Intelaf",
        place: "Ciudad de Guatemala",
        image: extraImage("photo-1624705002806-5d72df19c3ad"),
        specs: [
          ["Tamaño", "120 mm"],
          ["RPM", "180–1,800"],
          ["Flujo", "56.3 CFM"],
          ["Ruido", "0.3 sone"],
        ],
        score: 9.3,
        source: "https://www.arctic.de/en/P12-PWM-PST/ACFAN00137A",
      },
      {
        brand: "Corsair",
        model: "AF120 RGB Elite",
        price: "Q 249",
        shop: "Pacifiko",
        place: "Cobertura nacional",
        image: extraImage("photo-1625842268584-8f3296236761"),
        specs: [
          ["Tamaño", "120 mm"],
          ["RPM", "550–2,100"],
          ["Flujo", "65.57 CFM"],
          ["RGB", "8 zonas"],
        ],
        score: 9.0,
        source:
          "https://www.corsair.com/us/en/p/pc-cases/co-9050155-ww/af120-rgb-elite-120mm-pwm-fan-single-pack-co-9050155-ww",
      },
    ],
    recommend: "Arctic P12 PWM PST",
    why: "Un ventilador sobrio y eficiente que se puede encadenar para mejorar el flujo sin inflar el presupuesto.",
    ideal: "Cualquier armado · silencio",
  },
  {
    id: "speakers",
    number: "16",
    name: "Bocinas",
    short: "Sonido para compartir",
    group: "externo",
    tag: "Audio",
    products: [
      {
        brand: "Logitech",
        model: "Z207 Bluetooth",
        price: "Q 399",
        shop: "Walmart Guatemala",
        place: "Guatemala",
        image: extraImage("photo-1545454675-3531b543be5d"),
        specs: [
          ["Potencia", "10 W RMS"],
          ["Conexión", "Bluetooth + 3.5 mm"],
          ["Controles", "Volumen frontal"],
          ["Uso", "Escritorio"],
        ],
        score: 8.8,
        source:
          "https://www.logitech.com/en-us/products/speakers/z207-bluetooth-computer-speakers.980-001294.html",
      },
      {
        brand: "Creative",
        model: "Pebble V3 USB-C",
        price: "Q 349",
        shop: "Kemik",
        place: "Guatemala",
        image: extraImage("photo-1493225457124-a3eb161ffa5f"),
        specs: [
          ["Potencia", "8 W RMS"],
          ["Conexión", "USB-C + BT"],
          ["Controles", "Volumen frontal"],
          ["Uso", "Escritorio"],
        ],
        score: 8.9,
        source: "https://us.creative.com/p/speakers/creative-pebble-v3",
      },
    ],
    recommend: "Creative Pebble V3",
    why: "Un formato compacto, USB-C y Bluetooth que ocupa poco espacio y sirve tanto para estudio como entretenimiento.",
    ideal: "Estudio · oficina · hogar",
  },
  {
    id: "microphone",
    number: "17",
    name: "Micrófonos",
    short: "Tu voz, más clara",
    group: "externo",
    tag: "Creación",
    products: [
      {
        brand: "FIFINE",
        model: "K669B USB",
        price: "Q 399",
        shop: "Kemik",
        place: "Guatemala",
        image: extraImage("photo-1590602847861-f357a9332bbc"),
        specs: [
          ["Tipo", "Condensador"],
          ["Patrón", "Cardioide"],
          ["Conexión", "USB"],
          ["Uso", "Voz y streaming"],
        ],
        score: 8.8,
        source:
          "https://fifinemicrophone.com/products/fifine-k669b-usb-microphone",
      },
      {
        brand: "HyperX",
        model: "SoloCast USB",
        price: "Q 549",
        shop: "Intelaf",
        place: "Ciudad de Guatemala",
        image: extraImage("photo-1589939705384-5185137a7f0f"),
        specs: [
          ["Tipo", "Condensador"],
          ["Patrón", "Cardioide"],
          ["Conexión", "USB-C"],
          ["Extras", "Tap-to-mute"],
        ],
        score: 9.1,
        source: "https://hyperx.com/products/hyperx-solocast-usb-microphone",
      },
    ],
    recommend: "HyperX SoloCast USB",
    why: "El botón de silencio y la conexión USB-C simplifican videollamadas y creación de contenido.",
    ideal: "Clases · reuniones · streaming",
  },
  {
    id: "printer",
    number: "18",
    name: "Impresoras",
    short: "Del archivo al papel",
    group: "externo",
    tag: "Oficina",
    products: [
      {
        brand: "Epson",
        model: "EcoTank L3250",
        price: "Q 1,799",
        shop: "Office Depot Guatemala",
        place: "Guatemala",
        image: extraImage("photo-1612815154858-60aa4c59eaa6"),
        specs: [
          ["Tecnología", "Inyección · tanque"],
          ["Funciones", "Imprime · escanea · copia"],
          ["Conexión", "Wi-Fi"],
          ["Rendimiento", "Alto volumen"],
        ],
        score: 9.1,
        source:
          "https://epson.com/usa/For-Work/Printers/Inkjet/EcoTank-ET-2850-Wireless-Color-All-in-One-Cartridge-Free-Supertank-Printer/p/C11CJ63202",
      },
      {
        brand: "HP",
        model: "Smart Tank 580",
        price: "Q 1,699",
        shop: "Walmart Guatemala",
        place: "Guatemala",
        image: extraImage("photo-1562976540-1502c2145186"),
        specs: [
          ["Tecnología", "Inyección · tanque"],
          ["Funciones", "Imprime · escanea · copia"],
          ["Conexión", "Wi-Fi"],
          ["Control", "App HP Smart"],
        ],
        score: 8.9,
        source:
          "https://www.hp.com/us-en/shop/pdp/hp-smart-tank-580-wireless-all-in-one",
      },
    ],
    recommend: "Epson EcoTank L3250",
    why: "El tanque de tinta y el enfoque de alto volumen suelen resultar más convenientes para uso académico frecuente.",
    ideal: "Estudiantes · oficina · hogar",
  },
  {
    id: "external-ssd",
    number: "19",
    name: "SSD externo",
    short: "Tu biblioteca portátil",
    group: "externo",
    tag: "Movilidad",
    products: [
      {
        brand: "Samsung",
        model: "T7 Shield 1 TB",
        price: "Q 1,199",
        shop: "Pacifiko",
        place: "Cobertura nacional",
        image: extraImage("photo-1597872200969-2b65d56bd16b"),
        specs: [
          ["Interfaz", "USB 3.2 Gen 2"],
          ["Lectura", "Hasta 1,050 MB/s"],
          ["Protección", "IP65"],
          ["Formato", "Portátil"],
        ],
        score: 9.4,
        source:
          "https://semiconductor.samsung.com/consumer-storage/portable-ssd/t7-shield/",
      },
      {
        brand: "Kingston",
        model: "XS1000 1 TB",
        price: "Q 899",
        shop: "Intelaf",
        place: "Ciudad de Guatemala",
        image: extraImage("photo-1625842268584-8f3296236761"),
        specs: [
          ["Interfaz", "USB 3.2 Gen 2"],
          ["Lectura", "Hasta 1,050 MB/s"],
          ["Protección", "Carcasa metálica"],
          ["Formato", "Portátil"],
        ],
        score: 9.0,
        source: "https://www.kingston.com/en/ssd/xs1000-external-ssd",
      },
    ],
    recommend: "Kingston XS1000 1 TB",
    why: "Más compacto y accesible para transportar proyectos, respaldos y biblioteca multimedia.",
    ideal: "Estudiantes · respaldo · movilidad",
  },
  {
    id: "ups",
    number: "20",
    name: "UPS y reguladores",
    short: "Continuidad para tu equipo",
    group: "externo",
    tag: "Protección",
    products: [
      {
        brand: "Forza",
        model: "NT-1011 1000 VA",
        price: "Q 799",
        shop: "Intelaf",
        place: "Ciudad de Guatemala",
        image: extraImage("photo-1624705002806-5d72df19c3ad"),
        specs: [
          ["Capacidad", "1000 VA / 500 W"],
          ["Topología", "Interactiva"],
          ["Salidas", "8"],
          ["Protección", "Regulación AVR"],
        ],
        score: 8.8,
        source: "https://www.forzaups.com/product/nt-1011/",
      },
      {
        brand: "APC",
        model: "Back-UPS 650 VA",
        price: "Q 749",
        shop: "Office Depot Guatemala",
        place: "Guatemala",
        image: extraImage("photo-1582719478250-c89cae4dc85b"),
        specs: [
          ["Capacidad", "650 VA / 390 W"],
          ["Topología", "Interactiva"],
          ["Salidas", "8"],
          ["Protección", "AVR"],
        ],
        score: 9.0,
        source: "https://www.apc.com/us/en/product/BX650M1/",
      },
    ],
    recommend: "APC Back-UPS 650 VA",
    why: "Una marca reconocida y una capacidad adecuada para proteger un PC de oficina o gaming moderado.",
    ideal: "Oficina · estudio · protección eléctrica",
  },
  {
    id: "sound-card",
    number: "21",
    name: "Tarjetas de sonido",
    short: "Audio con más detalle",
    group: "interno",
    tag: "Audio",
    products: [
      {
        brand: "ASUS",
        model: "Xonar SE 5.1",
        price: "Q 499",
        shop: "Intelaf",
        place: "Ciudad de Guatemala",
        image: extraImage("photo-1598387993281-cecf8b71a8f8"),
        specs: [
          ["Audio", "5.1 canales"],
          ["Interfaz", "PCIe"],
          ["Resolución", "24-bit / 192 kHz"],
          ["Conexión", "3.5 mm · S/PDIF"],
        ],
        score: 8.8,
        source:
          "https://www.asus.com/motherboards-components/sound-cards/gaming/xonar-se/",
      },
      {
        brand: "Creative",
        model: "Sound Blaster Audigy FX",
        price: "Q 599",
        shop: "Pacifiko",
        place: "Cobertura nacional",
        image: extraImage("photo-1516280440614-37939bbacd81"),
        specs: [
          ["Audio", "5.1 canales"],
          ["Interfaz", "PCIe"],
          ["Resolución", "24-bit / 192 kHz"],
          ["Amplificador", "Audífonos integrado"],
        ],
        score: 9.0,
        source:
          "https://us.creative.com/p/sound-blaster/sound-blaster-audigy-fx",
      },
    ],
    recommend: "Creative Sound Blaster Audigy FX",
    why: "Entrega sonido envolvente, amplificación integrada y una mejora clara frente al audio básico de la placa madre.",
    ideal: "Música · gaming · edición de audio",
  },
  {
    id: "card-reader",
    number: "22",
    name: "Lectores de tarjetas",
    short: "Archivos sin fronteras",
    group: "externo",
    tag: "Movilidad",
    products: [
      {
        brand: "UGREEN",
        model: "USB-C SD / microSD",
        price: "Q 199",
        shop: "Kemik",
        place: "Guatemala",
        image: extraImage("photo-1544816155-12df9643f363"),
        specs: [
          ["Interfaz", "USB-C 3.0"],
          ["Formatos", "SD · microSD"],
          ["Velocidad", "Hasta 104 MB/s"],
          ["Compatibilidad", "Windows · macOS · Android"],
        ],
        score: 9.0,
        source: "https://www.ugreen.com/",
      },
      {
        brand: "Kingston",
        model: "MobileLite Plus USB 3.2",
        price: "Q 249",
        shop: "Intelaf",
        place: "Ciudad de Guatemala",
        image: extraImage("photo-1516321318423-f06f85e504b3"),
        specs: [
          ["Interfaz", "USB 3.2"],
          ["Formatos", "SD · microSD"],
          ["Velocidad", "Hasta 170 MB/s"],
          ["Compatibilidad", "Windows · macOS"],
        ],
        score: 9.1,
        source: "https://www.kingston.com/en/usb-flash-drives/mobilelite-plus",
      },
    ],
    recommend: "Kingston MobileLite Plus USB 3.2",
    why: "Su mayor velocidad resulta útil para fotógrafos, estudiantes y creadores que mueven archivos grandes con frecuencia.",
    ideal: "Fotografía · video · respaldos",
  },
  {
    id: "gamepad",
    number: "23",
    name: "Controles / gamepads",
    short: "Jugar también es interactuar",
    group: "externo",
    tag: "Gaming",
    products: [
      {
        brand: "Logitech",
        model: "F310",
        price: "Q 249",
        shop: "Intelaf",
        place: "Ciudad de Guatemala",
        image: extraImage("photo-1592840496694-26d035b52b48"),
        specs: [
          ["Conexión", "USB con cable"],
          ["Distribución", "XInput / DirectInput"],
          ["Controles", "Dos sticks · D-pad"],
          ["Compatibilidad", "PC · Steam"],
        ],
        score: 8.6,
        source:
          "https://www.logitechg.com/en-us/products/gamepads/f310-gamepad.940-000110.html",
      },
      {
        brand: "8BitDo",
        model: "Ultimate C 2.4G",
        price: "Q 499",
        shop: "Pacifiko",
        place: "Cobertura nacional",
        image: extraImage("photo-1600080972464-8e5e730b0b1c"),
        specs: [
          ["Conexión", "2.4 GHz inalámbrica"],
          ["Batería", "Hasta 25 horas"],
          ["Controles", "Hall effect sticks"],
          ["Compatibilidad", "PC · Steam Deck"],
        ],
        score: 9.2,
        source: "https://www.8bitdo.com/ultimate-c-2.4g-wireless-controller/",
      },
    ],
    recommend: "8BitDo Ultimate C 2.4G",
    why: "La conexión inalámbrica y la batería integrada ofrecen una experiencia más cómoda para jugar desde el escritorio o la sala.",
    ideal: "Gaming · emulación · Steam Deck",
  },
  {
    id: "projector",
    number: "24",
    name: "Proyectores",
    short: "Pantalla a otra escala",
    group: "externo",
    tag: "Entretenimiento",
    products: [
      {
        brand: "Epson",
        model: "CO-FH02 Full HD",
        price: "Q 4,999",
        shop: "Office Depot Guatemala",
        place: "Guatemala",
        image: extraImage("photo-1535016120720-40c646be5580"),
        specs: [
          ["Resolución", "1920 × 1080"],
          ["Brillo", "3,000 lúmenes"],
          ["Fuente", "Lámpara LED"],
          ["Conexión", "HDMI · Wi-Fi"],
        ],
        score: 9.1,
        source:
          "https://epson.com/usa/For-Home/Projectors/Streaming-Entertainment/CO-FH02-Full-HD-3LCD-Smart-Portable-Projector/p/V11HA85020",
      },
      {
        brand: "BenQ",
        model: "GV31 Full HD",
        price: "Q 4,499",
        shop: "Pacifiko",
        place: "Cobertura nacional",
        image: extraImage("photo-1489599849927-2ee91cede3ba"),
        specs: [
          ["Resolución", "1920 × 1080"],
          ["Brillo", "300 ANSI lúmenes"],
          ["Audio", "2.1 canales"],
          ["Conexión", "HDMI · inalámbrica"],
        ],
        score: 8.9,
        source: "https://www.benq.com/en-us/projector/portable/gv31.html",
      },
    ],
    recommend: "Epson CO-FH02 Full HD",
    why: "Su brillo superior ayuda a conservar una imagen más clara en espacios que no están completamente oscuros.",
    ideal: "Presentaciones · cine · aulas",
  },
  {
    id: "mousepad",
    number: "25",
    name: "Mouse pads",
    short: "Precisión de superficie",
    group: "externo",
    tag: "Gaming",
    products: [
      {
        brand: "Logitech",
        model: "G240 Cloth Gaming",
        price: "Q 199",
        shop: "Intelaf",
        place: "Ciudad de Guatemala",
        image: extraImage("photo-1616627982998-3b5c4c5b35bc"),
        specs: [
          ["Superficie", "Tela de baja fricción"],
          ["Tamaño", "340 × 280 mm"],
          ["Base", "Goma antideslizante"],
          ["Perfil", "1 mm"],
        ],
        score: 8.7,
        source:
          "https://www.logitechg.com/en-us/products/gaming-mouse-pads/g240-cloth-gaming-mouse-pad.943-000806.html",
      },
      {
        brand: "Razer",
        model: "Gigantus V2 Medium",
        price: "Q 249",
        shop: "Pacifiko",
        place: "Cobertura nacional",
        image: extraImage("photo-1629429408209-1f912961dbd8"),
        specs: [
          ["Superficie", "Tela microtejida"],
          ["Tamaño", "360 × 275 mm"],
          ["Base", "Goma antideslizante"],
          ["Perfil", "3 mm"],
        ],
        score: 9.0,
        source: "https://www.razer.com/gaming-mouse-mats/razer-gigantus-v2",
      },
    ],
    recommend: "Razer Gigantus V2 Medium",
    why: "Su superficie amplia y acolchada permite movimientos consistentes y mayor comodidad durante sesiones largas.",
    ideal: "Gaming · diseño · oficina",
  },
];
window.softwareCatalog = [
  {
    type: "Sistema operativo",
    name: "Windows 11",
    desc: "La plataforma más compatible para gaming, oficina y periféricos.",
    badge: "Compatibilidad",
    image: extraImage("photo-1517336714731-489689fd1ca8"),
    recommend: "Windows 11 Home",
    source: "https://www.microsoft.com/windows/windows-11",
  },
  {
    type: "Sistema operativo",
    name: "Ubuntu Linux",
    desc: "Alternativa abierta para aprender, programar y recuperar equipos.",
    badge: "Código abierto",
    image: extraImage("photo-1555066931-4365d14bab8c"),
    recommend: "Ubuntu 24.04 LTS",
    source: "https://ubuntu.com/download/desktop",
  },
  {
    type: "Productividad",
    name: "LibreOffice",
    desc: "Suite gratuita para documentos, hojas de cálculo y presentaciones.",
    badge: "Sin costo",
    image: extraImage("photo-1499750310107-5fef28a66643"),
    recommend: "LibreOffice",
    source: "https://www.libreoffice.org/",
  },
  {
    type: "Creación",
    name: "DaVinci Resolve",
    desc: "Edición de video, color y audio para proyectos audiovisuales.",
    badge: "Creadores",
    image: extraImage("photo-1492619375914-88005aa9e8fb"),
    recommend: "DaVinci Resolve",
    source: "https://www.blackmagicdesign.com/products/davinciresolve",
  },
  {
    type: "Desarrollo",
    name: "Visual Studio Code",
    desc: "Editor extensible para web, scripts y desarrollo de software.",
    badge: "Programación",
    image: extraImage("photo-1555066931-4365d14bab8c"),
    recommend: "VS Code",
    source: "https://code.visualstudio.com/",
  },
  {
    type: "Seguridad",
    name: "Bitdefender",
    desc: "Protección multicapa para navegación, archivos y amenazas comunes.",
    badge: "Protección",
    image: extraImage("photo-1563013544-824ae1b704d3"),
    recommend: "Bitdefender Antivirus Free",
    source: "https://www.bitdefender.com/consumer/antivirus",
  },
];

// Dos alternativas adicionales por categoría para completar la comparativa de cuatro marcas.
window.hardwareVariants = {
  procesadores: [
    ["AMD", "Ryzen 7 5700X", "Q 1,399"],
    ["Intel", "Core i7-12700F", "Q 2,099"],
  ],
  motherboards: [
    ["Gigabyte", "B550 AORUS Elite V2", "Q 1,449"],
    ["ASRock", "B550M Pro4", "Q 999"],
  ],
  ram: [
    ["Crucial", "Ballistix 16 GB DDR4", "Q 429"],
    ["XPG", "Gammix D20 16 GB DDR4", "Q 419"],
  ],
  gpu: [
    ["ASUS", "Dual RTX 4060 8 GB", "Q 2,899"],
    ["Sapphire", "Pulse RX 7600 8 GB", "Q 2,649"],
  ],
  storage: [
    ["Western Digital", "WD Blue SN580 1 TB", "Q 699"],
    ["Crucial", "P3 Plus 1 TB NVMe", "Q 649"],
  ],
  psu: [
    ["EVGA", "600 W1 80+ White", "Q 499"],
    ["Thermaltake", "Smart BX1 650W Bronze", "Q 649"],
  ],
  monitor: [
    ["ASUS", "TUF VG249Q1A 24”", "Q 1,499"],
    ["Acer", "Nitro KG241Y 24”", "Q 1,299"],
  ],
  keyboard: [
    ["Razer", "Ornata V3 X", "Q 599"],
    ["HyperX", "Alloy Origins Core", "Q 799"],
  ],
  mouse: [
    ["SteelSeries", "Rival 3", "Q 349"],
    ["HyperX", "Pulsefire Core", "Q 299"],
  ],
  audio: [
    ["Razer", "Barracuda X Wireless", "Q 899"],
    ["SteelSeries", "Arctis Nova 1", "Q 699"],
  ],
  network: [
    ["ASUS", "PCE-AX3000 Wi-Fi 6", "Q 599"],
    ["Intel", "I225-V 2.5GbE", "Q 449"],
  ],
  webcam: [
    ["Razer", "Kiyo Full HD", "Q 899"],
    ["AverMedia", "PW315 Full HD", "Q 699"],
  ],
  cooling: [
    ["Noctua", "NH-U12S redux", "Q 699"],
    ["be quiet!", "Pure Rock 2", "Q 549"],
  ],
  case: [
    ["Fractal Design", "Pop Air", "Q 1,099"],
    ["Thermaltake", "S200 TG ARGB", "Q 899"],
  ],
  fans: [
    ["Noctua", "NF-P12 redux 120 mm", "Q 199"],
    ["DeepCool", "FC120 3-pack", "Q 449"],
  ],
  speakers: [
    ["Edifier", "R980T 2.0", "Q 599"],
    ["Creative", "Pebble Plus", "Q 449"],
  ],
  microphone: [
    ["Blue", "Snowball iCE USB", "Q 599"],
    ["Razer", "Seiren Mini", "Q 499"],
  ],
  printer: [
    ["Canon", "PIXMA G3160", "Q 1,599"],
    ["Brother", "DCP-T520W", "Q 1,699"],
  ],
  "external-ssd": [
    ["SanDisk", "Extreme Portable SSD 1 TB", "Q 1,099"],
    ["Crucial", "X9 1 TB", "Q 949"],
  ],
  ups: [
    ["CyberPower", "CP1000AVRLCD", "Q 999"],
    ["Tripp Lite", "AVR750U", "Q 849"],
  ],
  "sound-card": [
    ["EVGA", "NU Audio", "Q 1,199"],
    ["SteelSeries", "GameDAC Gen 2", "Q 799"],
  ],
  "card-reader": [
    ["Anker", "USB-C 2-in-1 Card Reader", "Q 299"],
    ["Sabrent", "4-Slot USB Card Reader", "Q 349"],
  ],
  gamepad: [
    ["Xbox", "Wireless Controller", "Q 899"],
    ["GameSir", "G7 SE Wired", "Q 699"],
  ],
  projector: [
    ["ViewSonic", "PA503W WXGA", "Q 3,999"],
    ["Yaber", "V10 Full HD", "Q 2,499"],
  ],
  mousepad: [
    ["SteelSeries", "QcK Medium", "Q 179"],
    ["Corsair", "MM350 Extended", "Q 349"],
  ],
};
