// Modelos concretos y fuentes del fabricante. Las configuraciones varían por región.
window.deviceCatalog = {
  celulares: [
    { id: 'redmi-13', brand: 'Xiaomi', model: 'Redmi 13', tier: 'baja', source: 'https://www.mi.com/global/product/redmi-13/specs/', specs: [['Procesador', 'Helio G91-Ultra'], ['Pantalla', '6.79 pulgadas · 90 Hz'], ['Cámara principal', '108 MP'], ['Batería', '5030 mAh · carga de 33 W']], opinion: 'Yo lo elegiría para llamadas, redes y tareas diarias. Su pantalla grande me parece práctica, pero no lo compraría pensando en juegos exigentes.' },
    { id: 'galaxy-a16-5g', brand: 'Samsung', model: 'Galaxy A16 5G', tier: 'baja', source: 'https://www.samsung.com/uk/smartphones/galaxy-a/galaxy-a16-5g-blue-black-128gb-sm-a166bzkdeub/', specs: [['Pantalla', '6.7 pulgadas · Super AMOLED'], ['Conectividad', '5G'], ['Almacenamiento mostrado', '128 GB'], ['Batería', '5000 mAh']], opinion: 'Yo lo consideraría para uso cotidiano y una pantalla AMOLED sin irme a una gama superior. Confirmaría las bandas y la garantía de la versión vendida en Guatemala.' },
    { id: 'redmi-note-14', brand: 'Xiaomi', model: 'Redmi Note 14 (4G)', tier: 'baja', source: 'https://www.mi.com/global/product/redmi-note-14/specs/', specs: [['Procesador', 'Helio G99-Ultra'], ['Pantalla', 'AMOLED 6.67 pulgadas · 120 Hz'], ['Cámara principal', '108 MP'], ['Batería', '5500 mAh · 33 W']], opinion: 'Yo me quedaría con él si priorizo pantalla y batería para el día a día. Revisaría bien la caja: este es el modelo 4G, no la variante 5G.' },
    { id: 'galaxy-a56-5g', brand: 'Samsung', model: 'Galaxy A56 5G', tier: 'media', source: 'https://www.samsung.com/au/smartphones/galaxy-a/galaxy-a56-5g-awesome-graphite-128gb-sm-a566bzkkats/', specs: [['Pantalla', 'Super AMOLED 6.7 pulgadas · 120 Hz'], ['Cámara principal', '50 MP con estabilización óptica'], ['Batería', '5000 mAh'], ['Conectividad', '5G']], opinion: 'Yo lo elegiría como teléfono equilibrado para fotografías, estudio y trabajo diario. Antes de comprar, compararía capacidad de almacenamiento y garantía local.' },
    { id: 'poco-x7-pro', brand: 'POCO', model: 'X7 Pro', tier: 'media', source: 'https://www.mi.com/global/product/poco-x7-pro/specs/', specs: [['Procesador', 'Dimensity 8400-Ultra'], ['Pantalla', 'AMOLED 6.67 pulgadas · 120 Hz'], ['Memoria', 'LPDDR5X · almacenamiento UFS 4.0'], ['Batería global', '6000 mAh · 90 W']], opinion: 'Yo lo pondría primero si quiero jugar y mover aplicaciones exigentes dentro de esta gama. Confirmaría la versión regional porque la batería y los accesorios pueden variar.' },
    { id: 'redmi-note-14-pro-5g', brand: 'Xiaomi', model: 'Redmi Note 14 Pro 5G', tier: 'media', source: 'https://www.mi.com/global/product/redmi-note-14-pro-5g/specs/', specs: [['Procesador', 'Dimensity 7300-Ultra'], ['Pantalla', 'AMOLED 6.67 pulgadas · 120 Hz'], ['Cámara principal', '200 MP con estabilización óptica'], ['Conectividad', '5G']], opinion: 'Yo lo consideraría si me interesa más la cámara que buscar la máxima potencia para juegos. No decidiría solo por los megapíxeles: también miraría fotos de muestra.' },
    { id: 'iphone-16', brand: 'Apple', model: 'iPhone 16', tier: 'alta', source: 'https://www.apple.com/iphone-16/specs/', specs: [['Procesador', 'Apple A18'], ['Pantalla', 'OLED Super Retina XDR · 6.1 pulgadas'], ['Cámara principal', 'Fusion de 48 MP'], ['Conector', 'USB-C']], opinion: 'Yo lo elegiría si ya uso servicios y dispositivos de Apple. Me parece una opción compacta, pero revisaría cuánto almacenamiento necesito antes de pagar por una capacidad mayor.' },
    { id: 'galaxy-s25-ultra', brand: 'Samsung', model: 'Galaxy S25 Ultra', tier: 'alta', source: 'https://www.samsung.com/latin/smartphones/galaxy-s25-ultra/specs/', specs: [['Pantalla', 'AMOLED 6.9 pulgadas · hasta 120 Hz'], ['Cámara principal', '200 MP'], ['Herramienta integrada', 'S Pen'], ['Batería', '5000 mAh']], opinion: 'Yo lo consideraría para fotografía, productividad y notas con el S Pen. Su tamaño es importante: lo probaría en la mano antes de decidir.' },
    { id: 'xiaomi-15', brand: 'Xiaomi', model: 'Xiaomi 15', tier: 'alta', source: 'https://www.mi.com/global/product/xiaomi-15/specs/', specs: [['Procesador', 'Snapdragon 8 Elite'], ['Pantalla', 'AMOLED 6.36 pulgadas · 1–120 Hz'], ['Memoria', '12 GB · UFS 4.0'], ['Cámaras traseras', 'Tres cámaras de 50 MP']], opinion: 'Yo lo elegiría si busco potencia en un teléfono menos grande. Verificaría que sea la versión global y que tenga soporte y garantía en mi región.' },
  ],
  laptops: [
    { id: 'vivobook-go-e1504f', brand: 'ASUS', model: 'Vivobook Go 15 E1504F', tier: 'baja', source: 'https://www.asus.com/laptops/for-home/vivobook/vivobook-go-15-oled-e1504f/techspec/', specs: [['Procesador', 'Opciones Ryzen 3 7320U o Ryzen 5 7520U'], ['Pantalla', '15.6 pulgadas · variantes FHD LCD y OLED'], ['Gráficos', 'AMD Radeon integrados'], ['Formato', 'Laptop para tareas cotidianas']], opinion: 'Yo la consideraría para estudiar y trabajar con documentos. Revisaría la configuración exacta, especialmente la RAM y si la pantalla es LCD u OLED.' },
    { id: 'ideapad-slim3-15amn8', brand: 'Lenovo', model: 'IdeaPad Slim 3 15AMN8', tier: 'baja', source: 'https://psref.lenovo.com/WDProduct/IdeaPad_Slim_3_15AMN8', specs: [['Procesador', 'Opciones Ryzen 3 7320U o Ryzen 5 7520U'], ['Gráficos', 'Radeon 610M integrados'], ['Memoria', 'LPDDR5 soldada; hasta 16 GB según modelo'], ['Pantalla', '15.6 pulgadas; verificar panel del SKU']], opinion: 'Yo la usaría para clases y ofimática. Elegiría desde el principio la RAM necesaria, porque está soldada y no se puede ampliar con un módulo.' },
    { id: 'aspire3-a315-24p', brand: 'Acer', model: 'Aspire 3 A315-24P-R7VH', tier: 'baja', source: 'https://www.acer.com/us-en/laptops/aspire/aspire-3-amd/pdp/NX.KJBAA.001', specs: [['Procesador', 'Ryzen 3 7320U'], ['Memoria', '8 GB LPDDR5'], ['Almacenamiento', 'SSD de 128 GB en este SKU'], ['Pantalla', '15.6 pulgadas Full HD']], opinion: 'Yo la consideraría para tareas básicas si el precio acompaña. El SSD de esta configuración es pequeño, así que revisaría espacio disponible y posibilidad de ampliación.' },
    { id: 'macbook-air-m2', brand: 'Apple', model: 'MacBook Air 13 M2 (2022)', tier: 'media', source: 'https://support.apple.com/en-ie/111867', specs: [['Procesador', 'Apple M2 · CPU de 8 núcleos'], ['Pantalla', 'Liquid Retina de 13.6 pulgadas'], ['Conexiones', 'Dos Thunderbolt / USB 4 y MagSafe 3'], ['Memoria', 'Unificada; configuración de hasta 24 GB']], opinion: 'Yo la elegiría para llevar a clases o trabajar fuera de casa. Compraría la memoria y el almacenamiento que realmente necesito, porque no se amplían como en una PC de escritorio.' },
    { id: 'ideapad-slim5-14abr8', brand: 'Lenovo', model: 'IdeaPad Slim 5 14ABR8', tier: 'media', source: 'https://psref.lenovo.com/Detail/IdeaPad/IdeaPad_Slim_5_14ABR8?M=82XE000TSB', specs: [['Configuración de referencia', '82XE000TSB'], ['Procesador', 'Ryzen 5 7530U · 6 núcleos / 12 hilos'], ['Memoria', '16 GB DDR4 soldada'], ['Almacenamiento', 'SSD de 512 GB']], opinion: 'Yo la consideraría para programación y multitarea de estudio. Esta ficha corresponde a una configuración concreta; confirmaría que el equipo de la tienda tenga los mismos componentes.' },
    { id: 'vivobook15-m1502ya', brand: 'ASUS', model: 'Vivobook 15 M1502YA', tier: 'media', source: 'https://www.asus.com/in/laptops/for-home/vivobook/vivobook-15-m1502/techspec/', specs: [['Procesador de referencia', 'Ryzen 7 5825U · 8 núcleos / 16 hilos'], ['Gráficos', 'AMD Radeon integrados'], ['Pantalla', '15.6 pulgadas Full HD · 60 Hz'], ['Configuración', 'Confirmar RAM y SSD del SKU local']], opinion: 'Yo la elegiría para trabajo y multitarea si quiero una pantalla de tamaño cómodo. No la compararía con una laptop gaming con tarjeta gráfica dedicada.' },
    { id: 'zephyrus-g14-2024', brand: 'ASUS', model: 'ROG Zephyrus G14 GA403 (2024)', tier: 'alta', source: 'https://rog.asus.com/laptops/rog-zephyrus/rog-zephyrus-g14-2024/spec/', specs: [['Formato', 'Laptop gaming de 14 pulgadas'], ['Gráficos', 'RTX 4060 o RTX 4070 Laptop según SKU'], ['Pantalla', 'OLED; confirmar configuración regional'], ['Enfoque', 'Gaming y creación en formato compacto']], opinion: 'Yo la consideraría si necesito potencia gráfica sin cargar una laptop muy grande. Revisaría la GPU exacta y la refrigeración; una RTX de laptop no equivale a la versión de escritorio.' },
    { id: 'legion-pro5-16irx9', brand: 'Lenovo', model: 'Legion Pro 5 16IRX9', tier: 'alta', source: 'https://psref.lenovo.com/WDProduct/Legion_Pro_5_16IRX9', specs: [['Plataforma', 'Intel Core HX de 14.ª generación'], ['Gráficos', 'Opciones RTX 4050, 4060 o 4070 Laptop'], ['Pantalla', '16 pulgadas; resolución y Hz según SKU'], ['Memoria', 'DDR5; confirmar módulos instalados']], opinion: 'Yo la elegiría para jugar y trabajar con gráficos desde un escritorio. Antes de comprar compararía la GPU, su potencia configurada y el peso total con cargador.' },
    { id: 'macbook-pro14-m4', brand: 'Apple', model: 'MacBook Pro 14 M4 (2024)', tier: 'alta', source: 'https://support.apple.com/es-mx/121552', specs: [['Procesador', 'Apple M4 · CPU y GPU de 10 núcleos'], ['Pantalla', 'Liquid Retina XDR de 14.2 pulgadas'], ['Conexiones', 'Tres Thunderbolt 4, HDMI y SDXC'], ['Memoria', 'Unificada; elegir configuración al comprar']], opinion: 'Yo la consideraría para edición y trabajo creativo dentro de macOS. No pagaría por ella si mis tareas se resuelven bien con una laptop de gama media.' },
  ],
};
