// Personal editorial wording: preferences, without claiming hands-on testing.
window.albumNotes = {
  procesadores: "Yo me quedaría con el Ryzen 5 5600 si quiero armar una PC sin gastar de más. Prefiero dejar una parte del presupuesto para la gráfica y la memoria. Eso sí, primero revisaría que la tarjeta madre sea compatible con AM4.",
  motherboards: "Para un armado AMD con AM4, yo elegiría la ASUS TUF Gaming B550-Plus. Me interesa tener una buena base para ir mejorando el equipo. Si mi procesador fuera Intel, escogería una placa compatible con ese socket.",
  ram: "Yo escogería la Kingston FURY Beast de 16 GB. Para estudiar, trabajar y jugar, me gusta este punto de partida. Antes de comprar comprobaría que mi equipo use DDR4 y que el kit sea compatible.",
  gpu: "De estas opciones, yo elegiría la RTX 4060 para un equipo centrado en jugar a 1080p. Me llama la atención su enfoque en eficiencia. Si el presupuesto está más ajustado, compararía también el precio de la RX 7600.",
  storage: "Yo me quedaría con el Kingston NV2 si lo que busco es espacio para el sistema, juegos y tareas del día a día. No pagaría más solo por una cifra de velocidad: primero pensaría en el uso que realmente le voy a dar.",
  psu: "Yo elegiría la Corsair CX650 para un armado cuyo consumo esté dentro de su capacidad. En la fuente prefiero revisar protecciones, conectores y garantía; es una pieza en la que no compraría únicamente por el precio.",
  monitor: "Yo escogería el Samsung Odyssey G3 si mi prioridad es jugar. Para diseño o trabajo con color, también revisaría el tipo de panel y la calibración. La pantalla tiene que servir para lo que hago todos los días.",
  keyboard: "Yo me quedaría con el Redragon K552 si quiero empezar con un teclado mecánico sin subir demasiado el presupuesto. Revisaría la distribución de las teclas y el ruido de los switches, sobre todo si comparto el espacio.",
  mouse: "Yo elegiría el Logitech G203 como una opción para comenzar. Más que buscar el número de DPI más alto, me fijaría en que el tamaño y la forma se sientan cómodos para mi mano.",
  audio: "Yo escogería los Logitech G435 si quiero moverme sin estar pendiente del cable. Si voy a pasar muchas horas con ellos, priorizaría el ajuste y la comodidad antes que la apariencia.",
  network: "Para una PC de escritorio con una ranura PCIe compatible, yo elegiría el Archer TX55E. Si puedo llevar un cable de red hasta el equipo, también consideraría Ethernet. No lo compraría para una laptop sin comprobar el formato.",
  webcam: "Yo me quedaría con la Logitech C920s para clases y reuniones. También le daría importancia a la iluminación del escritorio: una buena cámara necesita un entorno que la acompañe.",
  cooling: "Yo elegiría el DeepCool AK400 Digital si encaja con mi procesador y gabinete. Antes de pensar en cómo se ve, revisaría el socket, la altura disponible y lo que necesita enfriar mi equipo.",
  case: "Yo escogería el NZXT H5 Flow si sus medidas encajan con mi armado. Me fijaría en el espacio para la gráfica, el disipador y los cables. Un gabinete bonito también tiene que ser práctico por dentro.",
  fans: "Yo me quedaría con los Arctic P12 PWM PST para un armado donde sean compatibles. Primero planearía por dónde entra y sale el aire; llenar el gabinete de ventiladores no siempre es la mejor solución.",
  speakers: "Yo elegiría las Creative Pebble V3 para un escritorio pequeño. Me gusta la idea de mantener el espacio despejado. Si quiero más volumen o graves, compararía también las otras opciones del grupo.",
  microphone: "Yo escogería el HyperX SoloCast para empezar con clases, reuniones o contenido. Lo acompañaría con una buena posición y un espacio tranquilo: el micrófono no puede hacer todo el trabajo por sí solo.",
  printer: "Yo me quedaría con la Epson EcoTank L3250 si voy a imprimir tareas con frecuencia. Antes de decidir, compararía el costo de las tintas, el mantenimiento y la garantía disponible en Guatemala.",
  "external-ssd": "Yo elegiría el Kingston XS1000 para llevar proyectos y respaldos. Revisaría el puerto del equipo y el cable para aprovecharlo. Y mantendría otra copia de mis archivos importantes.",
  ups: "Yo consideraría el APC Back-UPS, pero primero calcularía el consumo del equipo y la autonomía que necesito. La capacidad de una UPS debe ajustarse al armado; no elegiría solo por la marca.",
  "sound-card": "Yo consideraría la Creative Audigy FX si realmente necesito sus conexiones. Antes de comprarla, probaría el audio integrado de mi placa: si ya cubre lo que necesito, invertiría ese dinero en otra parte del equipo.",
  "card-reader": "Yo elegiría el Kingston MobileLite Plus después de revisar qué tarjetas uso y cuál versión del lector necesito. Para mí, la compatibilidad con el formato de la tarjeta va primero.",
  gamepad: "Yo escogería el 8BitDo Ultimate C si quiero jugar sin cable. Antes de comprarlo comprobaría la compatibilidad con mi sistema y mis juegos. También compararía la distribución de los botones.",
  projector: "Yo me quedaría con el Epson CO-FH02 para un espacio donde la luz sea una prioridad. Mediría la distancia de proyección y pensaría en la iluminación del lugar antes de decidir.",
  mousepad: "Yo elegiría el Razer Gigantus V2 si sus medidas encajan en mi escritorio. Me interesa tener espacio para mover el mouse con comodidad, sin quitarle lugar al teclado ni al resto del equipo.",
};
