
// Precios editoriales de referencia: confirmar en la tienda antes de publicar.
const components = [
  {
    id: "procesadores",
    number: "01",
    name: "Procesadores",
    short: "El pulso del sistema",
    group: "interno",
    tag: "Rendimiento",
    products: [
      {
        brand: "AMD",
        model: "Ryzen 5 5600",
        price: "Q 899",
        shop: "Intelaf",
        place: "Ciudad de Guatemala",
        image: "media/products/procesadores-amd-ryzen-5-5600.webp",
        specs: [
          ["Núcleos", "6 / 12 hilos"],
          ["Turbo", "Hasta 4.4 GHz"],
          ["Socket", "AM4"],
          ["Caché", "35 MB"],
        ],
        score: 8.9,
        source:
          "https://www.amd.com/en/products/processors/desktops/ryzen/5000-series/amd-ryzen-5-5600",
      },
      {
        brand: "Intel",
        model: "Core i5-12400F",
        price: "Q 1,099",
        shop: "Kemik",
        place: "Guatemala",
        image: "media/products/procesadores-intel-core-i5-12400f.webp",
        specs: [
          ["Núcleos", "6 / 12 hilos"],
          ["Turbo", "Hasta 4.4 GHz"],
          ["Socket", "LGA1700"],
          ["Caché", "18 MB"],
        ],
        score: 8.7,
        source:
          "https://www.intel.com/content/www/us/en/products/sku/134587/intel-core-i512400f-processor-18m-cache-up-to-4-40-ghz/specifications.html",
      },
    ],
    recommend: "AMD Ryzen 5 5600",
    why: "Su plataforma AM4 y el precio de referencia dejan más presupuesto para una GPU o memoria.",
    ideal: "Gaming 1080p · estudio · uso general",
  },
  {
    id: "motherboards",
    number: "02",
    name: "Tarjetas madre",
    short: "La placa que conecta todo",
    group: "interno",
    tag: "Compatibilidad",
    products: [
      {
        brand: "ASUS",
        model: "TUF Gaming B550-Plus",
        price: "Q 1,349",
        shop: "Intelaf",
        place: "Ciudad de Guatemala",
        image: "media/products/motherboards-asus-tuf-gaming-b550-plus.webp",
        specs: [
          ["Chipset", "AMD B550"],
          ["RAM", "4 × DDR4"],
          ["Formato", "ATX"],
          ["Red", "2.5 Gb Ethernet"],
        ],
        score: 9.1,
        source:
          "https://www.asus.com/motherboards-components/motherboards/tuf-gaming/tuf-gaming-b550-plus/",
      },
      {
        brand: "MSI",
        model: "PRO B660M-A WIFI DDR4",
        price: "Q 1,399",
        shop: "Pacifiko",
        place: "Cobertura nacional",
        image: "media/products/motherboards-msi-pro-b660m-a-wifi-ddr4.webp",
        specs: [
          ["Chipset", "Intel B660"],
          ["RAM", "4 × DDR4"],
          ["Formato", "mATX"],
          ["Red", "Wi-Fi 6"],
        ],
        score: 8.8,
        source: "https://www.msi.com/Motherboard/PRO-B660M-A-WIFI-DDR4",
      },
    ],
    recommend: "ASUS TUF Gaming B550-Plus",
    why: "Ofrece una ruta de actualización clara para AM4, conectividad rápida y construcción robusta.",
    ideal: "Armados AMD · gaming · creación",
  },
  {
    id: "ram",
    number: "03",
    name: "Memoria RAM",
    short: "Más espacio para crear",
    group: "interno",
    tag: "Calidad / precio",
    products: [
      {
        brand: "Kingston",
        model: "FURY Beast 16 GB DDR4",
        price: "Q 399",
        shop: "Intelaf",
        place: "Ciudad de Guatemala",
        image: "media/products/ram-kingston-fury-beast-16-gb-ddr4.webp",
        specs: [
          ["Capacidad", "16 GB (2 × 8)"],
          ["Velocidad", "3200 MT/s"],
          ["Latencia", "CL16"],
          ["Perfil", "XMP 2.0"],
        ],
        score: 9.2,
        source:
          "https://www.kingston.com/en/memory/gaming/kingston-fury-beast-ddr4-memory",
      },
      {
        brand: "Corsair",
        model: "Vengeance LPX 16 GB",
        price: "Q 449",
        shop: "Kemik",
        place: "Guatemala",
        image: "media/products/ram-corsair-vengeance-lpx-16-gb.webp",
        specs: [
          ["Capacidad", "16 GB (2 × 8)"],
          ["Velocidad", "3200 MHz"],
          ["Latencia", "CL16"],
          ["Perfil", "XMP 2.0"],
        ],
        score: 8.9,
        source: "https://www.corsair.com/us/en/p/memory/cmk16gx4m2e3200c16/",
      },
    ],
    recommend: "Kingston FURY Beast 16 GB DDR4",
    why: "La misma capacidad y frecuencia con un precio local de referencia más accesible.",
    ideal: "Gaming · multitarea · oficina",
  },
  {
    id: "gpu",
    number: "04",
    name: "Tarjetas gráficas",
    short: "La imagen cobra vida",
    group: "interno",
    tag: "Gaming",
    products: [
      {
        brand: "NVIDIA",
        model: "GeForce RTX 4060 8 GB",
        price: "Q 2,799",
        shop: "Pacifiko",
        place: "Cobertura nacional",
        image: "media/products/gpu-nvidia-geforce-rtx-4060-8-gb.webp",
        specs: [
          ["VRAM", "8 GB GDDR6"],
          ["Interfaz", "PCIe 4.0"],
          ["Tecnologías", "DLSS 3 · RT"],
          ["Consumo", "115 W"],
        ],
        score: 9.1,
        source:
          "https://www.nvidia.com/en-us/geforce/graphics-cards/40-series/rtx-4060-4060ti/",
      },
      {
        brand: "AMD",
        model: "Radeon RX 7600 8 GB",
        price: "Q 2,599",
        shop: "Intelaf",
        place: "Ciudad de Guatemala",
        image: "media/products/gpu-amd-radeon-rx-7600-8-gb.webp",
        specs: [
          ["VRAM", "8 GB GDDR6"],
          ["Interfaz", "PCIe 4.0"],
          ["Tecnologías", "FSR · AV1"],
          ["Consumo", "165 W"],
        ],
        score: 8.8,
        source: "https://www.amd.com/en/products/graphics/amd-radeon-rx-7600",
      },
    ],
    recommend: "GeForce RTX 4060 8 GB",
    why: "DLSS 3 y un consumo menor inclinan la balanza para un equipo gaming eficiente.",
    ideal: "Gaming 1080p · streaming",
  },
  {
    id: "storage",
    number: "05",
    name: "Almacenamiento",
    short: "Velocidad que se siente",
    group: "interno",
    tag: "Más rápido",
    products: [
      {
        brand: "Kingston",
        model: "NV2 1 TB NVMe",
        price: "Q 599",
        shop: "Intelaf",
        place: "Ciudad de Guatemala",
        image: "media/products/storage-kingston-nv2-1-tb-nvme.webp",
        specs: [
          ["Interfaz", "PCIe 4.0 NVMe"],
          ["Lectura", "Hasta 3,500 MB/s"],
          ["Formato", "M.2 2280"],
          ["Garantía", "3 años"],
        ],
        score: 8.9,
        source: "https://www.kingston.com/en/ssd/nv2-nvme-pcie-ssd",
      },
      {
        brand: "Samsung",
        model: "990 EVO 1 TB",
        price: "Q 999",
        shop: "Pacifiko",
        place: "Cobertura nacional",
        image: "media/products/storage-samsung-990-evo-1-tb.webp",
        specs: [
          ["Interfaz", "PCIe 5.0 / 4.0"],
          ["Lectura", "Hasta 5,000 MB/s"],
          ["Formato", "M.2 2280"],
          ["Garantía", "5 años"],
        ],
        score: 9.4,
        source:
          "https://semiconductor.samsung.com/consumer-storage/internal-ssd/990-evo/",
      },
    ],
    recommend: "Kingston NV2 1 TB NVMe",
    why: "Para la mayoría de estudiantes y gamers, entrega el salto real de NVMe sin pagar por velocidad que quizá no se aproveche.",
    ideal: "Uso general · gaming · oficina",
  },
  {
    id: "psu",
    number: "06",
    name: "Fuente de poder",
    short: "Energía con criterio",
    group: "interno",
    tag: "Seguridad",
    products: [
      {
        brand: "Corsair",
        model: "CX650 650W 80+ Bronze",
        price: "Q 699",
        shop: "Intelaf",
        place: "Ciudad de Guatemala",
        image: "media/products/psu-corsair-cx650-650w-80-bronze.webp",
        specs: [
          ["Potencia", "650 W"],
          ["Certificación", "80+ Bronze"],
          ["Modularidad", "No modular"],
          ["Protecciones", "OVP · OPP · SCP"],
        ],
        score: 9.0,
        source:
          "https://www.corsair.com/us/en/p/psu/cp-9020278-na/cx-series-cx650-650-watt-80-plus-bronze-atx-power-supply-cp-9020278-na",
      },
      {
        brand: "Cooler Master",
        model: "MWE Bronze V2 650W",
        price: "Q 749",
        shop: "Kemik",
        place: "Guatemala",
        image: "media/products/psu-cooler-master-mwe-bronze-v2-650w.webp",
        specs: [
          ["Potencia", "650 W"],
          ["Certificación", "80+ Bronze"],
          ["Modularidad", "No modular"],
          ["Ventilador", "120 mm HDB"],
        ],
        score: 8.8,
        source:
          "https://www.coolermaster.com/catalog/power-supplies/mwe-series/mwe-bronze-v2-650/",
      },
    ],
    recommend: "Corsair CX650",
    why: "Buena base de seguridad para un armado de gama media y una referencia local competitiva.",
    ideal: "Armados de gama media",
  },
  {
    id: "monitor",
    number: "07",
    name: "Monitores",
    short: "Donde todo aparece",
    group: "externo",
    tag: "Productividad",
    products: [
      {
        brand: "LG",
        model: "24MP400-B 24” IPS",
        price: "Q 999",
        shop: "Walmart Guatemala",
        place: "Guatemala",
        image: "media/products/monitor-lg-24mp400-b-24-ips.webp",
        specs: [
          ["Panel", "IPS"],
          ["Resolución", "1920 × 1080"],
          ["Frecuencia", "75 Hz"],
          ["Puertos", "HDMI · VGA"],
        ],
        score: 8.8,
        source: "https://www.lg.com/us/monitors/lg-24mp400-b",
      },
      {
        brand: "Samsung",
        model: "Odyssey G3 24” 144 Hz",
        price: "Q 1,399",
        shop: "Intelaf",
        place: "Ciudad de Guatemala",
        image: "media/products/monitor-samsung-odyssey-g3-24-144-hz.webp",
        specs: [
          ["Panel", "VA"],
          ["Resolución", "1920 × 1080"],
          ["Frecuencia", "144 Hz"],
          ["Puertos", "HDMI · DP"],
        ],
        score: 9.2,
        source:
          "https://www.samsung.com/us/computing/monitors/gaming/24-odyssey-g3-gaming-monitor-ls24ag300nnxza/",
      },
    ],
    recommend: "Samsung Odyssey G3",
    why: "Los 144 Hz y Adaptive Sync aportan una diferencia tangible para jugar, sin abandonar el formato accesible de 24 pulgadas.",
    ideal: "Gaming · estudio · diseño",
  },
  {
    id: "keyboard",
    number: "08",
    name: "Teclados",
    short: "Cada entrada cuenta",
    group: "externo",
    tag: "Oficina + gaming",
    products: [
      {
        brand: "Logitech",
        model: "G413 SE Mecánico",
        price: "Q 649",
        shop: "Pacifiko",
        place: "Cobertura nacional",
        image: "media/products/keyboard-logitech-g413-se-mecanico.webp",
        specs: [
          ["Tipo", "Mecánico"],
          ["Switches", "Táctiles"],
          ["Layout", "Español"],
          ["Conexión", "USB"],
        ],
        score: 8.9,
        source:
          "https://www.logitechg.com/en-us/products/gaming-keyboards/g413-se-mechanical-gaming-keyboard.920-010436.html",
      },
      {
        brand: "Redragon",
        model: "K552 Kumara RGB",
        price: "Q 399",
        shop: "Kemik",
        place: "Guatemala",
        image: "media/products/keyboard-redragon-k552-kumara-rgb.webp",
        specs: [
          ["Tipo", "Mecánico"],
          ["Switches", "Outemu Blue"],
          ["Layout", "Español"],
          ["Conexión", "USB"],
        ],
        score: 8.7,
        source: "https://www.redragonshop.com/products/redragon-k552",
      },
    ],
    recommend: "Redragon K552 Kumara RGB",
    why: "Es la puerta de entrada mecánica con la mejor relación entre sensación, funciones y precio de referencia.",
    ideal: "Estudiantes · gaming · programación",
  },
  {
    id: "mouse",
    number: "09",
    name: "Mouse",
    short: "Precisión en la mano",
    group: "externo",
    tag: "Valor",
    products: [
      {
        brand: "Logitech",
        model: "G203 Lightsync",
        price: "Q 249",
        shop: "Intelaf",
        place: "Ciudad de Guatemala",
        image: "media/products/mouse-logitech-g203-lightsync.webp",
        specs: [
          ["Sensor", "HERO 8K"],
          ["DPI", "Hasta 8,000"],
          ["Botones", "6 programables"],
          ["Conexión", "Cable USB"],
        ],
        score: 9.0,
        source:
          "https://www.logitechg.com/en-us/products/gaming-mice/g203-lightsync-rgb-gaming-mouse.910-005790.html",
      },
      {
        brand: "Razer",
        model: "DeathAdder Essential",
        price: "Q 299",
        shop: "Pacifiko",
        place: "Cobertura nacional",
        image: "media/products/mouse-razer-deathadder-essential.webp",
        specs: [
          ["Sensor", "Óptico 6,400 DPI"],
          ["DPI", "Hasta 6,400"],
          ["Botones", "5"],
          ["Conexión", "Cable USB"],
        ],
        score: 8.7,
        source: "https://www.razer.com/gaming-mice/razer-deathadder-essential",
      },
    ],
    recommend: "Logitech G203 Lightsync",
    why: "Ofrece un sensor preciso, seis botones y una referencia de precio muy competitiva para empezar.",
    ideal: "Gaming casual · oficina",
  },
  {
    id: "audio",
    number: "10",
    name: "Audio",
    short: "Escuchar también es diseñar",
    group: "externo",
    tag: "Inmersión",
    products: [
      {
        brand: "HyperX",
        model: "Cloud Stinger 2",
        price: "Q 549",
        shop: "Intelaf",
        place: "Ciudad de Guatemala",
        image: "media/products/audio-hyperx-cloud-stinger-2.webp",
        specs: [
          ["Audio", "DTS Headphone:X"],
          ["Micrófono", "Flexible"],
          ["Conexión", "3.5 mm"],
          ["Peso", "275 g"],
        ],
        score: 8.9,
        source:
          "https://hyperx.com/products/hyperx-cloud-stinger-2-wired-gaming-headset",
      },
      {
        brand: "Logitech",
        model: "G435 LIGHTSPEED",
        price: "Q 699",
        shop: "Pacifiko",
        place: "Cobertura nacional",
        image: "media/products/audio-logitech-g435-lightspeed.webp",
        specs: [
          ["Audio", "Dolby Atmos"],
          ["Micrófono", "Dual beamforming"],
          ["Conexión", "Wireless + BT"],
          ["Peso", "165 g"],
        ],
        score: 9.1,
        source:
          "https://www.logitechg.com/en-us/products/gaming-audio/g435-wireless-bluetooth-gaming-headset.981-001049.html",
      },
    ],
    recommend: "Logitech G435 LIGHTSPEED",
    why: "Su peso reducido y conexión inalámbrica resuelven más escenarios cotidianos, aunque exige un presupuesto mayor.",
    ideal: "Gaming · clases · movilidad",
  },
  {
    id: "network",
    number: "11",
    name: "Redes",
    short: "Conexión sin interrupciones",
    group: "externo",
    tag: "Conectividad",
    products: [
      {
        brand: "TP-Link",
        model: "Archer TX55E Wi-Fi 6",
        price: "Q 499",
        shop: "Kemik",
        place: "Guatemala",
        image: "media/products/network-tp-link-archer-tx55e-wi-fi-6.webp",
        specs: [
          ["Estándar", "Wi-Fi 6 AX3000"],
          ["Velocidad", "2,402 Mbps"],
          ["Bluetooth", "5.2"],
          ["Interfaz", "PCIe"],
        ],
        score: 9.0,
        source:
          "https://www.tp-link.com/us/home-networking/pci-adapter/archer-tx55e/",
      },
      {
        brand: "TP-Link",
        model: "TG-3468 Gigabit Ethernet",
        price: "Q 159",
        shop: "Intelaf",
        place: "Ciudad de Guatemala",
        image: "media/products/network-tp-link-tg-3468-gigabit-ethernet.webp",
        specs: [
          ["Estándar", "Gigabit Ethernet"],
          ["Velocidad", "10/100/1000"],
          ["Conexión", "PCIe"],
          ["Uso", "Baja latencia"],
        ],
        score: 8.5,
        source: "https://www.tp-link.com/us/home-networking/adapter/tg-3468/",
      },
    ],
    recommend: "Archer TX55E Wi-Fi 6",
    why: "Para una laptop o escritorio que necesita flexibilidad, Wi-Fi 6 y Bluetooth cubren más necesidades en una sola tarjeta.",
    ideal: "Hogar · gaming · streaming",
  },
  {
    id: "webcam",
    number: "12",
    name: "Webcams",
    short: "Presencia a distancia",
    group: "externo",
    tag: "Creador",
    products: [
      {
        brand: "Logitech",
        model: "C920s Pro HD",
        price: "Q 799",
        shop: "Pacifiko",
        place: "Cobertura nacional",
        image: "media/products/webcam-logitech-c920s-pro-hd.webp",
        specs: [
          ["Video", "1080p / 30 fps"],
          ["Lente", "78° diagonal"],
          ["Micrófono", "Estéreo"],
          ["Privacidad", "Obturador"],
        ],
        score: 9.1,
        source:
          "https://www.logitech.com/en-us/products/webcams/c920s-pro-hd-webcam.960-001257.html",
      },
      {
        brand: "AverMedia",
        model: "PW315 Full HD",
        price: "Q 699",
        shop: "Kemik",
        place: "Guatemala",
        image: "media/products/webcam-avermedia-pw315-full-hd.webp",
        specs: [
          ["Video", "1080p / 60 fps"],
          ["Lente", "95° diagonal"],
          ["Micrófono", "Dual"],
          ["Privacidad", "Tapa física"],
        ],
        score: 8.8,
        source: "https://www.avermedia.com/product-detail/PW315",
      },
    ],
    recommend: "Logitech C920s Pro HD",
    why: "Es una referencia conocida para clases, reuniones y creación de contenido con una imagen consistente.",
    ideal: "Clases · reuniones · contenido",
  },
];

components.push(...(window.hardwareExtras || []));
const variantSourceByBrand = {
  AMD: "https://www.amd.com/",
  Intel: "https://www.intel.com/",
  ASUS: "https://www.asus.com/",
  MSI: "https://www.msi.com/",
  Gigabyte: "https://www.gigabyte.com/",
  ASRock: "https://www.asrock.com/",
  Kingston: "https://www.kingston.com/",
  Corsair: "https://www.corsair.com/",
  NVIDIA: "https://www.nvidia.com/",
  "Western Digital": "https://www.westerndigital.com/",
  Samsung: "https://www.samsung.com/",
  Crucial: "https://www.crucial.com/",
  EVGA: "https://www.evga.com/",
  Thermaltake: "https://www.thermaltake.com/",
  LG: "https://www.lg.com/",
  Acer: "https://www.acer.com/",
  Razer: "https://www.razer.com/",
  HyperX: "https://hyperx.com/",
  Logitech: "https://www.logitech.com/",
  SteelSeries: "https://steelseries.com/",
  Noctua: "https://noctua.at/",
  "be quiet!": "https://www.bequiet.com/",
  "Fractal Design": "https://www.fractal-design.com/",
  DeepCool: "https://www.deepcool.com/",
  Edifier: "https://www.edifier.com/",
  Blue: "https://www.bluemic.com/",
  Canon: "https://www.usa.canon.com/",
  Brother: "https://www.brother-usa.com/",
  SanDisk: "https://www.sandisk.com/",
  CyberPower: "https://www.cyberpowersystems.com/",
  TrippLite: "https://tripplite.eaton.com/",
  Netgear: "https://www.netgear.com/",
};
Object.entries(window.hardwareVariants || {}).forEach(([id, variants]) => {
  const category = components.find((item) => item.id === id);
  if (!category) return;
  variants.forEach(([brand, model, price, variantImage], index) => {
    category.products.push({
      brand,
      model,
      price,
      shop: "Disponibilidad por confirmar",
      place: "Consultar distribuidores en Guatemala",
      image: variantImage,
      specs: [["Ficha técnica", "Consultar especificaciones del modelo en el fabricante"]],
      source: variantSourceByBrand[brand] || "",
    });
  });
});


window.applyCatalogTiers(components);
window.hardwareCatalog = components;

